### ISSUE TITLE
Add a new extern method for removing a pending transaction

### ISSUE THREAD

**Issue by Spl3en** [icon-project/multisig-wallet#20]
A new method should be implemented that allow any wallet owner to remove a pending transaction, if the confirmation count == 0.

Otherwise, let's say a wallet owner has submitted a transaction but he wants to cancel it afterwards, the unwanted pending transaction will remain pending forever.

**Comment by soobokjin** [comment]
I think this feature is reasonable and need to be implemented. After Finish other works, I will implement this feature. Thank you for your consistent interest..

**Comment by goldworm-icon** [comment]
Thanks for your interest on multisig wallet.
I think your idea is excellent.
But unfortunately, we are too busy to work on this right now, so I guess it would be done after September.
:(
Anyway thank you for your excellent idea, and we will try to apply it as soon as possible.

**Comment by Spl3en** [comment]
@soobokjin @goldworm-icon Hey, thanks for the answers.
I'll write the feature and submit a pull request for reviewing if that can help.
