### ISSUE TITLE
setStake from a multisig wallet

### ISSUE THREAD

**Issue by Spl3en** [icon-project/multisig-wallet#25]
Hello,

I don't seem to be able to execute the IISSS API `setStake` from the multisig wallet.

Here's the transaction params for creating the multisig tx : https://tracker.icon.foundation/transaction/0x77916c15e4d7dcd50ed53ab1d77b0944889493af254ab4746221791243d0bfb3

The [transaction call](https://tracker.icon.foundation/transaction/0xd54e11fe290e1550099828f442c41113983684a458e05b6615536258c7cb65c5) fails to be called when enough confirmation is reached (`ExecutionFailure`) : 
![https://i.imgur.com/bmkxR1J.png](https://i.imgur.com/bmkxR1J.png)

```
Transaction result: {
    "jsonrpc": "2.0",
    "result": {
        "txHash": "0xd54e11fe290e1550099828f442c41113983684a458e05b6615536258c7cb65c5",
        "blockHeight": "0xdccf0d",
        "blockHash": "0x9d95d33ce4c0d483c3e47089c9137640b63b1f6d4f6ba4c430b9f178edb39f28",
        "txIndex": "0x1",
        "to": "cx87fda925272496ae3f0bdeb551dad8fd29e0c7cf",
        "stepUsed": "0x4ef5c",
        "stepPrice": "0x2540be400",
        "cumulativeStepUsed": "0x4ef5c",
        "eventLogs": [
            {
                "scoreAddress": "cx87fda925272496ae3f0bdeb551dad8fd29e0c7cf",
                "indexed": [
                    "Confirmation(Address,int)",
                    "hxa881b4caabd19c498cdf20a110bb00ccdd553ff6",
                    "0x2"
                ],
                "data": []
            },
            {
                "scoreAddress": "cx87fda925272496ae3f0bdeb551dad8fd29e0c7cf",
                "indexed": [
                    "ExecutionFailure(int)",
                    "0x2"
                ],
                "data": []
            }
        ],
        "logsBloom": "0x00020000000000080000100000000000000000000000000000000000000000000000010000002000000000000000000000000000000000000000000000000000000001000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000800000000000400000000000000000000000004000000000000000000000000000000000000000000000020000000000000000000000000000000000000800000000000000000000000000000000000000000000000000080000002000000000000200004000000000000000000000000000000000000800000000000000000000000000000080000000000",
        "status": "0x1"
    },
    "id": 1
}
```

Is there a restriction from calling the `cx0000000000000000000000000000000000000000` ICON Service contract from the multisig wallet ?

Cheers

**Comment by soobokjin** [comment]
Yes, there is a restriction to calling the 'cx0000000000000000000000000000000000000000' (i.e. system SCORE) from the normal SCORE (include multisig wallet). we did not consider calling the system SCORE using internal call. I'll leave a message after checking if we should provide this feature. Thank you!

**Comment by goldworm-icon** [comment]
We discussed this issue and determined to support SCORE internal call for special contract cx000...000. But unfortunately, this feature will be available in mid June when the next ICON version will be released.
Thank you for your consistent interest on ICON.

**Comment by Spl3en** [comment]
Great, thanks for the quick reply. No problem about waiting until the next ICON version, glad to hear it's going to be implemented 👍
