### ISSUE TITLE
Is it possible to transfer ICX to another SCORE?

### ISSUE THREAD

**Issue by mr-rooftop** [icon-project/multisig-wallet#28]
Can't figure out how to send ICX to another SCORE from the multisig wallet.
Seems like I have to explicitly call a method. But to enter the `fallback` function, it's needed to send ICX with `self.icx.send()` or `self.icx.transfer`.

https://github.com/icon-project/multisig-wallet/blob/72201bd59bffd374930542d95fbb129a3ca9a85b/multisig_wallet/multisig_wallet.py#L238

Do I misunderstand something, or is it simply not possible to transfer ICX to another SCORE?
If not, when do you plan to enable it?

**Comment by Spl3en** [comment]
You're right, this multisig wallet cannot transfer ICX to another SCOREs. You may be interested in looking at ICONSafe's implementation (ICONation's multisig wallet), we solved that issue by checking additionnally if the [method_name is defined](https://github.com/iconation/ICONSafe-SCORE/blob/master/ICONSafe/transaction_manager/transaction_manager.py#L173).

**Comment by sink772** [comment]
@Spl3en I'm sorry but you are wrong. The multisig wallet absolutely can transfer ICX to another SCOREs without calling a method explicitly (in this case, of course, `fallback` would be called).  You can find the complete example of this case in the following code snippet.

https://github.com/icon-project/icon-testsuite/blob/1255c483456bb07b2f50097b0312fafd002d8ef6/test/java/foundation/icon/test/cases/MultiSigWalletTest.java#L108

@mr-rooftop You can treat a SCORE address like a EOA when you just want to send ICX to the SCORE.  If you had tested this scenario by yourself, you probably knew it earlier.

**Comment by mr-rooftop** [comment]
Thanks for the fast answers to both of you!

@sink772 Thanks for the clarification and the link to the snippet.
I tested it out in the wrong way, now it works with your help!

Just to round things up: What is an EOA?

**Comment by Spl3en** [comment]
Thanks for the clarification @sink772 , but I'm still wondering how does it work ?
Even though I read the unit test code, I cannot understand how the ICX get transfered.

Here's the MSW code : 
```py
            if transaction.destination.is_contract:
                self.call(addr_to=transaction.destination,
                          func_name=method_name,
                          kw_dict=method_params,
                          amount=transaction.value)
            else:
                self.icx.transfer(transaction.destination, transaction.value)
```

So in that case, self.call is called.
Is `self.call` call the `fallback` method if the `func_name` is None ? As it's not documented, it's not easy to guess


@mr-rooftop : An EOA is an Externally Owned Acccount, so any ICON address owned by ICONists, in other words not a SCORE contract address.

**Comment by sink772** [comment]
@Spl3en In short, yes, `fallback` would be called when you didn't specify the method name explicitly.  In this case, the method name would be `None` in Python and `null` in Java.

As you already know, `fallback` is a special method that is executed when the method was not given in the transaction (by its definition). This is same for the inter-SCORE call.  Actually we don't need to separate the ICX transfer operation according to the target address.  FYI, in the Java version of MultiSigWallet, the transfer operation didn't be separated.

https://github.com/icon-project/java-score-examples/blob/6f9d9d323ee78cc87ad8c02d4a71e1c7332387fb/multisig-wallet/src/main/java/com/iconloop/score/example/MultiSigWallet.java#L392

**Comment by mr-rooftop** [comment]
@Spl3en if I recall correctly, at first it didn't work when I specified the `method_name` with an empty string `""`.

But after @sink772 's comment, I simply left out the `method_name` altogether which succeeds (taken from my python integration test):
```
params = {"_destination": self._score_address,
          "_value": value,
          "_description": "send ICX to fallback function"}
```
